apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks5-proxy
  namespace: clusters-agreeneguest
  labels:
    app: socks5-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socks5-proxy
  template:
    metadata:
      labels:
        app: socks5-proxy
    spec:
      containers:
      - name: socks5-proxy
        image: quay.io/agreene/socks5-proxy:6
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/konnectivity-proxy-tls
          name: oas-konnectivity-proxy-cert
      volumes:
      - name: oas-konnectivity-proxy-cert
        secret:
          defaultMode: 420
          secretName: konnectivity-client