apiVersion: v1
kind: Service
metadata:
  name: socks5-proxy
  namespace: clusters-agreeneguest
spec:
  selector:
    app: socks5-proxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080