apiVersion: v1
kind: Service
metadata:
  name: socks5-proxy
  namespace: openshift-operator-lifecycle-manager
spec:
  selector:
    app: socks5-proxy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000